### PR TITLE
Ml krr refactor

### PR DESCRIPTION
**Pull request by jomsdev**
- Created a new folder KRR inside ml.

- The folder KRR contains all the functionalities related with KRR from KrrParams to featured_map_condition.

### CODE REVIEW

**Comment by haimav** [comment]
1) Just wondering about the logic behind this refactor...
2) Maybe rlsc.hpp should move too to its own folder? Need to understand why the refactor was done to begin with.

**Comment by jomsdev** [comment]
1. It would be better organize the things in a more structured way. 

    - Right now all is well structured, but some names can introduce some confusion (for example [skylark_krr.cpp](), it is an "executable" not where the krr functions live #52  ).  Ban had this confusion, and I had it before,  I thought it would be good make it easier for future contributors.

    -  Many functions in krr.hpp are very similar (kernelRdige, approximateKernelRidge, FasterKernelRidge, etc..) Now we are putting macros there to expose them to the CAPI. It's going to be a bit chaotic, maybe a file per function + macro is easier to debug. All are .hpp so the compile time does not be affected.

2. Let me check the content of the file (WIP)

**Comment by haimav** [comment]
OK, but I think the filenames should be lower case separated with _.
i.e. approximateKernelRidge -> approximate_kernel_ridge

**Comment by jomsdev** [comment]
I agree with you. It is more readable with the words separated by underscores. I was trying to keep the convention of having the same name as the function and capitalize the classes (for example BaseKernel.hpp)

**Pull request merged**
