### PR TITLE
kernel_container_t has a _type attribute.

### PR DESCRIPTION
**Pull request by jomsdev**
It give us information about which kenrel is. std::_type = (linear, gaussian, etc...)

### CODE REVIEW

**Comment by haimav** [comment]
Why is it needed?

**Comment by jomsdev** [comment]
Debugging

For example, if KernelRige is throwing some error and we want to know if it is related to the kernel that is passed. We could check it when we are creating the kernel but it's better if the container 'has all the information'. It would be easier to debug then.

**Comment by haimav** [comment]
Good point, but can't we use RTTI for that? That said, it might easier to work with the _type as you implemented.

**Comment by jomsdev** [comment]
see #43 for more information

**Pull request closed without merging**
